java:
    8home:  /usr/lib/jvm/java-8-openjdk-amd64
spinfer:
    home:   /Users/anil.koyuncu/projects/fixminer/spinfer/spinfer.native
coccinelle:
    home:   /Users/anil.koyuncu/projects/fixminer/spinfer/statics

dataset:
#    home:   /Users/anilkoyuncu/projects/fixminer/fixminer-core/python/data/gumInputLinux

    inputPath : /root/Fixminer-miner/fixminer-data/patches
    repo:   /root/Fixminer-miner/fixminer-data/datasets

fixminer:
    projectType : java
    datapath: /root/Fixminer-miner/fixminer-data/



    pjName : patches
    portDumps : 6399
    numOfWorkers : 14
    hostname : localhost
    hunkLimit : 2
    patchSize : 50


    projectList : fuse
    inputPath : /root/Fixminer-miner/fixminer-data/patches
    redisPath : /root/Fixminer-miner/python/data/redis
    srcMLPath :  /usr/local/bin/srcml
